export const workProjects = [
  {
    title: 'Harrow & Calloway',
    category: 'Legal Services',
    status: 'CASEFLOW READY',
    code: 'AX-041',
    niche: 'LEGAL',
    homepage: false,
    weakness: 'Dense copy, buried trust signals, and no clear intake path.',
    changed: 'A sharper case-type structure, proof-forward pages, and a focused consultation path.',
    result: 'A firm presence that feels established before the first call.',
  },
  {
    title: 'Aurelia Dental Studio',
    category: 'Healthcare & Medical',
    status: 'TRUST SYSTEM',
    code: 'AX-031',
    niche: 'HEALTH',
    homepage: true,
    weakness: 'Generic healthcare layout with slow trust-building and weak mobile scanning.',
    changed: 'Procedure pages, proof placement, and a calmer appointment path.',
    result: 'Patients understand care quality faster and can act without hunting.',
  },
  {
    title: 'Blackline Barber Co.',
    category: 'Personal Services & Grooming',
    status: 'BOOKING PATH',
    code: 'AX-027',
    niche: 'GROOMING',
    homepage: true,
    weakness: 'Strong local service, but the site did not communicate polish or booking confidence.',
    changed: 'A tighter brand system, service menu hierarchy, and direct booking route.',
    result: 'The shop reads premium while keeping the path to a chair short.',
  },
  {
    title: 'Lacquer Nail Studio',
    category: 'Salon & Beauty',
    status: 'LIVE DEMO',
    code: 'AX-014',
    niche: 'BEAUTY',
    homepage: true,
    weakness: 'Visual quality lived on social channels, while the website felt thin.',
    changed: 'A high-trust service experience with booking cues, service proof, and mobile-first flow.',
    result: 'A studio presence that feels booked, polished, and easy to choose.',
  },
  {
    title: 'Ember & Oak Kitchen',
    category: 'Restaurant & Hospitality',
    status: 'MENU FLOW',
    code: 'AX-052',
    niche: 'HOSPITALITY',
    homepage: false,
    weakness: 'Menu, hours, and reservation intent were split across too many paths.',
    changed: 'A tighter hospitality surface with menu rhythm, location clarity, and reservation priority.',
    result: 'Guests get the essentials fast without losing the atmosphere.',
  },
  {
    title: 'Summit Grounds Co.',
    category: 'Landscaping & Outdoor Services',
    status: 'QUOTE SYSTEM',
    code: 'AX-063',
    niche: 'OUTDOOR',
    homepage: false,
    weakness: 'The offer was seasonal, scattered, and hard to quote from.',
    changed: 'Service-area proof, quote routing, and package framing for local buyers.',
    result: 'More qualified quote intent with less explanation required.',
  },
  {
    title: 'Ridge & Crown Roofing',
    category: 'Roofing & Exteriors',
    status: 'LEAD ROUTE',
    code: 'AX-071',
    niche: 'EXTERIORS',
    homepage: false,
    weakness: 'Emergency and replacement buyers could not quickly separate services.',
    changed: 'Urgency-based pathways, proof placement, and conversion-focused service pages.',
    result: 'The site routes higher-intent visitors before they bounce to competitors.',
  },
];

export const processSteps = [
  {
    title: 'Review',
    body: 'We audit the current site, offer, proof, and points where visitors lose trust.',
    signal: 'TRUST LOSS MAP',
  },
  {
    title: 'Scope',
    body: 'We lock the pages, conversion paths, structure, and priorities before design starts.',
    signal: 'PATH LOCKED',
  },
  {
    title: 'Build',
    body: 'We design, write, develop, and test the site in production-ready form.',
    signal: 'SYSTEM ASSEMBLY',
  },
  {
    title: 'Launch',
    body: 'We connect the domain, verify performance, and hand over a live system.',
    signal: 'LIVE CHECKS',
  },
];

export const pricingPlans = [
  {
    name: 'Subscription',
    tag: 'Preferred Path',
    price: 'Starts at $150/mo',
    description: 'Low upfront cost with hosting, support, and ongoing edits included.',
    features: [
      'Up to 5 pages',
      'Hosting included',
      'Ongoing edits and support',
      'Month-to-month after launch',
      'Full ownership available at month 12',
      '3 rounds of revisions',
    ],
  },
  {
    name: 'Ownership Build',
    price: 'Starts at $3,500',
    description: 'One payment. Full code ownership at launch.',
    features: [
      'Up to 5 pages',
      'Full code ownership at launch',
      'Launch support included',
      'Hosting scoped separately',
      'SEO foundation',
      '3 rounds of revisions',
    ],
  },
  {
    name: 'E-commerce / Rebuilds',
    price: 'Custom',
    description: 'Scoped builds for stores, migrations, and larger systems.',
    features: [
      'Store setup or rebuild',
      'Migration support',
      'Integrations as needed',
      'Launch support included',
      'Scoped pricing',
      'Scoped revisions',
    ],
  },
];

export const whyAxiomPoints = [
  ['No unclear offer.', 'If a visitor cannot understand what you do in seconds, the page is not finished.'],
  ['No buried proof.', 'Reviews, past work, and trust signals belong where buyers actually look.'],
  ['No slow first load.', 'Performance is not a bonus. It is part of the sale.'],
  ['No dead-end handoff.', 'Monthly clients keep support. Ownership clients get a clean exit.'],
];
